[project]
name = "local-llm"
version = "1.0.1"
description = "Local LLM runner"
readme = "README.md"
license = {text = "MIT"}
authors = [
    { name = "batusaribay", email = "batusaribay@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.2",
    "rich>=15.0.0",
]

[project.scripts]
local-llm = "local_llm:main"
uncensored-llm = "local_llm:main"

[tool.uv.build-backend]
data-files = { "local_llm" = ["models.json"] }

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
