[project]
name = "uncensored-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = {text = "MIT"}
authors = [
    { name = "p4p2r0", email = "294768138+p4p2r0@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.2",
]

[project.scripts]
uncensored-llm = "uncensored_llm:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
